services:
  backend:
    build: ./backend
    container_name: asset-backend
    volumes:
      - ./backend/data:/app/data

  frontend:
    build: ./frontend
    container_name: asset-frontend
    depends_on:
      - backend

  nginx-proxy:
    image: nginx:alpine
    container_name: asset-nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend